import { ApiError } from '@/shared/http/client'

const messages: Record<string, string> = {
  WEB_NOT_CONFIGURED: '尚未填写搜索密钥。请填写后测试，或导入启动环境配置。',
  WEB_AUTHENTICATION_FAILED: '搜索密钥无效或无权访问，请更换密钥后重新测试。',
  WEB_RATE_LIMITED: '搜索服务请求受限，请检查额度并稍后测试。',
  WEB_TIMEOUT: '搜索服务响应超时，请检查网络后重试。',
  WEB_CONNECTION_FAILED: '无法连接搜索服务，请检查网络后重试。',
  WEB_PROVIDER_FAILED: '搜索服务暂时不可用，请稍后重试。',
  WEB_INVALID_RESPONSE: '搜索服务返回了无法识别的结果，请稍后重试。',
  INVALID_CREDENTIAL: '请填写完整密钥；不能将已显示的掩码作为密钥保存。',
  INVALID_EMBEDDING_CONFIG: '请检查模型、超时和批量设置。',
  INVALID_EMBEDDING_ADDRESS: '请填写有效服务地址。远程 API 使用 HTTPS；远程 Ollama 地址需在启动配置中设为可信。',
  OLLAMA_GATEWAY_AUTH_UNSUPPORTED: '本地 Ollama 不需要 API key；带鉴权的网关请选择兼容 API。',
  EMBEDDING_NOT_CONFIGURED: 'Embedding 尚未配置凭据，请填写服务对应的 API key。',
  EMBEDDING_AUTHENTICATION_FAILED: 'Embedding 凭据无效或权限不足，请更换密钥后测试。',
  EMBEDDING_RATE_LIMITED: 'Embedding 服务请求受限，请稍后重试。',
  EMBEDDING_TIMEOUT: 'Embedding 服务响应超时，请检查服务或增加超时后重试。',
  EMBEDDING_CONNECTION_FAILED: '无法连接 Embedding 服务，请检查地址和服务运行状态。',
  EMBEDDING_MODEL_NOT_FOUND: 'Ollama 未安装所选模型或模型版本已变化，请确认模型后重新测试。',
  EMBEDDING_INVALID_RESPONSE: 'Embedding 接口返回无效向量。聊天接口可用不能证明此接口可用。',
  EMBEDDING_DIMENSION_MISMATCH: '服务返回的向量维度已变化，请重新测试并建立新索引。',
  EMBEDDING_PROVIDER_FAILED: 'Embedding 接口暂时不可用，请检查服务的 /embeddings 接口。',
  EMBEDDING_BUSY: 'Embedding 服务正在处理请求，请稍后重试。',
  UNSUPPORTED_DIMENSIONS: '当前支持 1–4096 维，请选择支持范围内的模型。',
  EMBEDDING_TEST_EXPIRED: '验证已过期或配置已变化，请重新测试后保存。',
  SETTINGS_CHANGED: '配置已被其他操作更新，请重新加载最新设置。',
  REBUILD_ALREADY_RUNNING: '已有索引正在准备或等待启用，请先启用或放弃该任务。',
  REBUILD_NOT_READY: '索引尚未准备完成，请刷新状态后再操作。',
  INDEX_GENERATION_MISMATCH: '当前索引已变化，请重新建立候选索引。',
  SOURCE_VERSION_MISMATCH: '语料内容已变化，请重试重建；原索引保持可用。',
  HELP_INDEX_NOT_READY: '尚无可用帮助语料，请检查后端随包文档后重试。',
  OLLAMA_UNAVAILABLE: 'Embedding 计算失败，请检查服务、模型版本和实际维度后重试。',
  RETRIEVAL_UNAVAILABLE: '检索服务暂时不可用，请确认 Java 与 Python 服务已启动。',
  INTERRUPTED_BY_RESTART: '重建因服务重启中断，原索引保持不变，请重试。',
  NETWORK_ERROR: '无法连接应用服务，请确认后端已启动后重试。',
}
export function serviceMessage(code: string) { return messages[code] ?? '操作未完成，请检查服务设置后重试。' }
export function serviceError(error: unknown) { return { code: error instanceof ApiError ? error.code : 'UNKNOWN_ERROR' } }
