import { test, expect } from './helpers'

// Started by the isolated Java integration fixture. No mocked application API or synthetic host events.
test('actual broker/Python/UI stream, reconnect, turns, refresh, navigation and cancellation', async ({ page, context }) => {
  test.setTimeout(240_000)
  test.skip(!process.env.SPEC_AGENT_GA_BROWSER_THREAD, 'Requires isolated Java/Python integration fixture')
  const thread = process.env.SPEC_AGENT_GA_BROWSER_THREAD!
  const project = process.env.SPEC_AGENT_GA_BROWSER_PROJECT!
  await page.addInitScript(({ thread }) => {
    localStorage.setItem('spec-agent:global-assistant:thread:v1', thread)
    localStorage.setItem('spec-agent:global-assistant:panel:v1', 'open')
  }, { thread })
  await page.goto('/projects')
  await expect(page.getByTestId('ga-panel')).toBeVisible()
  const composer = page.getByTestId('ga-composer-input')
  await composer.fill(`请调用 project.get_summary，projectId 是 ${project}，读取真实概要后，用约 250 字中文说明结果，不要导航。`)
  await page.getByTestId('ga-send').click()
  await expect(page.getByTestId('ga-streaming')).toBeVisible({ timeout: 100_000 })
  // Interrupt the actual browser connection while the durable host run continues.
  await context.setOffline(true)
  await page.waitForTimeout(1500)
  await context.setOffline(false)
  await expect(page.getByTestId('ga-stop')).toHaveCount(0, { timeout: 100_000 })
  await expect(page.getByTestId('ga-streaming')).toHaveCount(0, { timeout: 100_000 })
  const first = page.getByTestId('ga-turn').first()
  await expect(first.getByTestId('ga-process-toggle')).toBeVisible()
  const firstRun = await first.getAttribute('data-run-id')
  await first.getByTestId('ga-process-toggle').click()
  await expect(first.getByTestId('ga-tool-activity')).toHaveCount(1)
  await expect(first).not.toContainText('进行中')
  await page.reload()
  await expect(page.locator(`[data-run-id="${firstRun}"]`).getByTestId('ga-process-toggle')).toBeVisible()
  await expect(page.locator(`[data-run-id="${firstRun}"]`).getByTestId('ga-process-details')).toBeHidden()
  await composer.fill(`请只调用 ui.navigate，destination 为 PROJECT，resourceId 为 ${project}，打开这个项目。`)
  await page.getByTestId('ga-send').click()
  await page.waitForURL(new RegExp(`/projects/${project}`), { timeout: 100_000 })
  await expect(page.getByTestId('ga-streaming')).toHaveCount(0, { timeout: 100_000 })
  await expect(page.getByTestId('ga-turn')).toHaveCount(2)
  await page.goto('/projects')
  await page.reload()
  await expect(page.getByTestId('ga-turn')).toHaveCount(2)
  // Restoring historical navigation must not execute it again.
  await expect(page).toHaveURL(/\/projects$/)
  await composer.fill('浏览器取消验收：请开始输出，等待我取消。')
  await page.getByTestId('ga-send').click()
  await expect(page.getByTestId('ga-streaming')).toContainText('取消前实际传输草稿', { timeout: 30_000 })
  await page.getByTestId('ga-stop').click()
  await expect(page.getByTestId('ga-streaming')).toHaveCount(0)
  await expect(page.getByTestId('ga-status')).toHaveCount(0)
  await page.reload()
  await expect(page.getByTestId('ga-turn')).toHaveCount(3)
  await expect(page.getByTestId('ga-timeline')).not.toContainText('取消前实际传输草稿')
  await expect(page.getByTestId('ga-timeline')).not.toContainText('进行中')
  await page.getByTestId('ga-panel').screenshot({ path: process.env.SPEC_AGENT_GA_BROWSER_SCREENSHOT ?? 'test-results/ga-real-turns.png' })
})
