package com.specagent.retrieval.config;

import java.util.Set;

public final class ServiceSettingsErrors {
    private ServiceSettingsErrors() {}
    public static String safeCode(RuntimeException ex) {
        String code=ex.getMessage();
        return code!=null && Set.of("INVALID_CREDENTIAL","INVALID_EMBEDDING_CONFIG","INVALID_EMBEDDING_ADDRESS","EMBEDDING_NOT_CONFIGURED",
            "EMBEDDING_AUTHENTICATION_FAILED","EMBEDDING_RATE_LIMITED","EMBEDDING_PROVIDER_FAILED","EMBEDDING_INVALID_RESPONSE",
            "EMBEDDING_DIMENSION_MISMATCH","EMBEDDING_CONNECTION_FAILED","EMBEDDING_TIMEOUT","EMBEDDING_BUSY","EMBEDDING_INTERRUPTED",
            "EMBEDDING_MODEL_NOT_FOUND","EMBEDDING_TEST_EXPIRED","OLLAMA_GATEWAY_AUTH_UNSUPPORTED","UNSUPPORTED_DIMENSIONS","SETTINGS_CHANGED",
            "UNSUPPORTED_PROFILE","STALE_SCOPE_GRANT","STALE_WORKLOAD","SOURCE_VERSION_MISMATCH","INDEX_GENERATION_MISMATCH",
            "DEADLINE_EXCEEDED","INVALID_VECTOR","REBUILD_NOT_READY","REBUILD_ALREADY_RUNNING","HELP_INDEX_NOT_READY","RETRIEVAL_UNAVAILABLE",
            "OLLAMA_UNAVAILABLE","INTERRUPTED_BY_RESTART","UNSUPPORTED_CORPUS").contains(code)?code:"SERVICE_SETTINGS_FAILED";
    }
}
